name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI:
    name: Static checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      - name: Vet
        run: go vet ./...

      - name: copyright_notice
        run: ./scripts/check-copyright-notice.sh

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
